package com.hotelmanager.web.exception;

public enum ErrorCode {
    RESERVATION_OVERLAP,
    INVALID_DATES,
    ROOM_NOT_AVAILABLE,
    INVALID_STATE_TRANSITION,
    CHECKIN_NOT_ALLOWED,
    CHECKOUT_NOT_ALLOWED,
    DUPLICATE_CHECKIN,
    CAPACITY_EXCEEDED,
    CANCEL_NOT_ALLOWED,
    RESOURCE_NOT_FOUND,
    FORBIDDEN,
    CONFLICT
}
