-- =============================================================================
-- V10__room_stays.sql
-- Hotel Manager -- Historial de ocupacion por habitacion (ER-16 de
-- docs/hotel-rules.md §4). Dialecto: PostgreSQL 16. Ejecutado tras V9.
--
-- Crea:
--   * room_stays (ER-16) Historial de estancias de una habitacion asociada a
--     una reserva. Permite registrar cambios de habitacion durante una estancia
--     (ER-16.1..ER-16.5): se cierra el room_stay actual (actual_check_out) y se
--     crea uno nuevo para la habitacion destino.
--
-- Notas:
--   * check_in / check_out son DATE (planificadas); actual_check_in /
--     actual_check_out son TIMESTAMPTZ (instante real del movimiento).
--   * Sin EXCLUDE GiST aqui: una misma habitacion puede tener varios room_stays
--     consecutivos para reservas distintas; el backend valida la coherencia
--     contra reservation_rooms (que si tiene EXCLUDE).
-- =============================================================================
CREATE TABLE room_stays (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    reservation_id   BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    check_in         DATE NOT NULL,
    check_out        DATE NOT NULL,
    actual_check_in  TIMESTAMPTZ,
    actual_check_out TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT room_stays_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_room_stays_room_id        ON room_stays (room_id);
CREATE INDEX idx_room_stays_reservation_id ON room_stays (reservation_id);
CREATE INDEX idx_room_stays_check_in       ON room_stays (check_in);
CREATE INDEX idx_room_stays_check_out      ON room_stays (check_out);
