-- =============================================================================
-- V3__refresh_tokens.sql
-- Hotel Manager -- Tabla refresh_tokens para el flujo de auth con rotacion.
-- Dialecto: PostgreSQL 16. Ejecutado por Flyway tras V2.
--
-- Permite persistir refresh tokens con:
--   * Almacenamiento del HASH (SHA-256) del token, nunca el token original.
--   * jti (JWT ID) unico para identificar el token emitido.
--   * Rotacion: al usarse un refresh token, se revoca (revoked_at) y se apunta
--     al jti del token que lo reemplazo (replaced_by_jti).
--   * Deteccion de reutilizacion: si se presenta un token ya revocado, el
--     backend revoca toda la cadena (todos los refresh_tokens del usuario o
--     cadena ligada por replaced_by_jti) y devuelve 401.
--   * Expiracion: expires_at > created_at (CHECK). Limpieza periodica por
--     expires_at o revoked_at la hace el backend / job de mantenimiento.
--
-- Contrato: docs/fix-plan.md seccion 3.1 y docs/database.md seccion 9.
-- =============================================================================
CREATE TABLE refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    jti             TEXT NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    replaced_by_jti TEXT,
    device_info     TEXT,
    CONSTRAINT refresh_tokens_check_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_jti        ON refresh_tokens (jti);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
