-- =============================================================================
-- V5__rate_engine.sql
-- Hotel Manager -- Motor tarifario (ER-1..ER-6.2 de docs/hotel-rules.md §1).
-- Dialecto: PostgreSQL 16. Ejecutado por Flyway tras V4.
--
-- Crea:
--   * rate_plans            (ER-1)  Planes tarifarios por tipo de habitacion.
--   * seasonal_rates        (ER-2)  Temporadas con multiplicador o precio absoluto.
--   * daily_rate_overrides  (ER-3)  Precios especiales por fecha concreta.
--   * promotion_rules       (ER-4)  Descuentos condicionales con vigencia.
--   * closed_dates          (ER-6.2) Fechas cerradas para llegada (CTA) / salida (CTD).
--   * taxes_and_fees        (ER-5)  Impuestos y cargos configurables con vigencia.
--
-- Convenciones (heredadas de V1):
--   * IDs: BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   * Dinero: NUMERIC(12,2).
--   * Fechas calendario: DATE (sin zona horaria).
--   * Marcas de auditoria: TIMESTAMPTZ, DEFAULT now().
--   * JSONB para arrays tarifarios (7 valores lun-dom).
--
-- Notas:
--   * rate_plans.cancellation_policy_id se declara aqui como BIGINT nullable SIN
--     FK. La FK a cancellation_policies se anade en V7 (esa tabla no existe aun).
--   * seasonal_rates previene solapamiento por plan con EXCLUDE USING gist sobre
--     (rate_plan_id, overlap_range), patron identico al de reservation_rooms en
--     V1. Requiere btree_gist (ya instalado en V1; se repite por seguridad).
--   * daily_rate_overrides y closed_dates usan UNIQUE ... NULLS NOT DISTINCT
--     (PostgreSQL 15+) para que rate_plan_id / room_type_id NULL no permitan
--     duplicados (NULL = "aplica a cualquier plan / tipo").
--   * weekday_rates y weekdays se validan como array JSONB de 7 numeros >= 0
--     mediante jsonb_path_exists (inmutable, permitido en CHECK).
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -----------------------------------------------------------------------------
-- rate_plans  (ER-1)
--   Plan tarifario para un tipo de habitacion. weekday_rates = 7 valores
--   lun-dom (NUMERIC(12,2) >= 0). cancellation_policy_id nullable (FK en V7).
-- -----------------------------------------------------------------------------
CREATE TABLE rate_plans (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   TEXT NOT NULL UNIQUE,
    name                   TEXT NOT NULL,
    room_type_id           BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    weekday_rates          JSONB NOT NULL,
    adult_extra_rate       NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (adult_extra_rate >= 0),
    child_extra_rate       NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (child_extra_rate >= 0),
    cancellation_policy_id BIGINT,
    min_nights             INT NOT NULL DEFAULT 1 CHECK (min_nights >= 1),
    max_nights             INT,
    is_default             BOOLEAN NOT NULL DEFAULT FALSE,
    active                 BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from             DATE,
    valid_to               DATE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rate_plans_max_nights_chk     CHECK (max_nights IS NULL OR max_nights > min_nights),
    CONSTRAINT rate_plans_valid_dates_chk    CHECK (valid_to IS NULL OR valid_from <= valid_to),
    CONSTRAINT rate_plans_weekday_rates_chk  CHECK (
        jsonb_typeof(weekday_rates) = 'array'
        AND jsonb_array_length(weekday_rates) = 7
        AND NOT jsonb_path_exists(weekday_rates, '$[*] ? (@.type() != "number")')
        AND NOT jsonb_path_exists(weekday_rates, '$[*] ? (@.type() == "number" && @ < 0)')
    )
);

CREATE INDEX idx_rate_plans_room_type_id ON rate_plans (room_type_id);
CREATE INDEX idx_rate_plans_active       ON rate_plans (active);
-- code ya tiene indice UNIQUE implicito (rate_plans_code_key).

-- -----------------------------------------------------------------------------
-- seasonal_rates  (ER-2)
--   Temporada dentro de un plan tarifario. price_mode = MULTIPLIER (weekdays =
--   7 multiplicadores NUMERIC) o ABSOLUTE (weekdays = 7 precios NUMERIC(12,2)).
--   Prevencion de solapamiento por plan: EXCLUDE USING gist sobre
--   (rate_plan_id, overlap_range), donde overlap_range es una columna generada
--   STORED a partir de daterange(start_date, end_date, '[)'] (patron V1).
-- -----------------------------------------------------------------------------
CREATE TABLE seasonal_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_plan_id  BIGINT NOT NULL REFERENCES rate_plans(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    season_type   TEXT NOT NULL CHECK (season_type IN ('ALTA', 'MEDIA', 'BAJA')),
    price_mode    TEXT NOT NULL CHECK (price_mode IN ('MULTIPLIER', 'ABSOLUTE')),
    weekdays      JSONB NOT NULL,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(start_date, end_date, '[)')) STORED,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT seasonal_rates_end_gt_start_chk CHECK (end_date > start_date),
    CONSTRAINT seasonal_rates_weekdays_chk     CHECK (
        jsonb_typeof(weekdays) = 'array'
        AND jsonb_array_length(weekdays) = 7
        AND NOT jsonb_path_exists(weekdays, '$[*] ? (@.type() != "number")')
        AND NOT jsonb_path_exists(weekdays, '$[*] ? (@.type() == "number" && @ < 0)')
    )
);

CREATE INDEX idx_seasonal_rates_rate_plan_id ON seasonal_rates (rate_plan_id);
CREATE INDEX idx_seasonal_rates_start_date   ON seasonal_rates (start_date);
CREATE INDEX idx_seasonal_rates_end_date     ON seasonal_rates (end_date);

ALTER TABLE seasonal_rates
    ADD CONSTRAINT seasonal_rates_no_overlap
    EXCLUDE USING gist (rate_plan_id WITH =, overlap_range WITH &&);

-- -----------------------------------------------------------------------------
-- daily_rate_overrides  (ER-3)
--   Override de precio para una fecha concreta + tipo de habitacion + plan.
--   rate_plan_id NULL = aplica a cualquier plan. Maxima prioridad (ER-7).
--   UNIQUE (room_type_id, rate_plan_id, date) NULLS NOT DISTINCT: con
--   rate_plan_id NULL, solo puede existir un override por (room_type_id, date).
-- -----------------------------------------------------------------------------
CREATE TABLE daily_rate_overrides (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE CASCADE,
    date         DATE NOT NULL,
    price        NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    reason       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (room_type_id, rate_plan_id, date)
);

CREATE INDEX idx_daily_rate_overrides_date         ON daily_rate_overrides (date);
CREATE INDEX idx_daily_rate_overrides_room_type_id ON daily_rate_overrides (room_type_id);

-- -----------------------------------------------------------------------------
-- promotion_rules  (ER-4)
--   Promocion con descuento condicional (PERCENTAGE o FIXED), vigencia,
--   restricciones de noches / huespedes, plan opcional (NULL = cualquier plan).
-- -----------------------------------------------------------------------------
CREATE TABLE promotion_rules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           TEXT NOT NULL UNIQUE,
    description    TEXT,
    discount_type  TEXT NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FIXED')),
    discount_value NUMERIC(12,2) NOT NULL CHECK (discount_value >= 0),
    min_nights     INT NOT NULL DEFAULT 1 CHECK (min_nights >= 1),
    min_guests     INT NOT NULL DEFAULT 1 CHECK (min_guests >= 1),
    valid_from     DATE,
    valid_to       DATE,
    rate_plan_id   BIGINT REFERENCES rate_plans(id) ON DELETE CASCADE,
    stackable      BOOLEAN NOT NULL DEFAULT FALSE,
    priority       INT NOT NULL DEFAULT 0,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT promotion_rules_pct_chk       CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100),
    CONSTRAINT promotion_rules_valid_dates_chk CHECK (valid_to IS NULL OR valid_from <= valid_to)
);

CREATE INDEX idx_promotion_rules_active     ON promotion_rules (active);
CREATE INDEX idx_promotion_rules_valid_from ON promotion_rules (valid_from);
-- code ya tiene indice UNIQUE implicito (promotion_rules_code_key).

-- -----------------------------------------------------------------------------
-- closed_dates  (ER-6.2)
--   Fecha cerrada para llegada (closed_arrival) y/o salida (closed_departure).
--   room_type_id NULL = aplica a todos los tipos. UNIQUE (room_type_id, date)
--   NULLS NOT DISTINCT: con room_type_id NULL, solo un cierre por fecha.
-- -----------------------------------------------------------------------------
CREATE TABLE closed_dates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id     BIGINT REFERENCES room_types(id) ON DELETE CASCADE,
    date             DATE NOT NULL,
    closed_arrival   BOOLEAN NOT NULL DEFAULT FALSE,
    closed_departure BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE NULLS NOT DISTINCT (room_type_id, date)
);

CREATE INDEX idx_closed_dates_date ON closed_dates (date);

-- -----------------------------------------------------------------------------
-- taxes_and_fees  (ER-5)
--   Impuesto (TAX_PERCENT) o cargo fijo (FEE_FIXED) con vigencia temporal.
--   applies_to: ROOM_RATE (sobre suma de tarifas), TOTAL (sobre total tras
--   otros impuestos), PER_NIGHT (por noche individual).
-- -----------------------------------------------------------------------------
CREATE TABLE taxes_and_fees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    type        TEXT NOT NULL CHECK (type IN ('TAX_PERCENT', 'FEE_FIXED')),
    rate_value  NUMERIC(12,2) NOT NULL CHECK (rate_value >= 0),
    applies_to  TEXT NOT NULL CHECK (applies_to IN ('ROOM_RATE', 'TOTAL', 'PER_NIGHT')),
    valid_from  DATE,
    valid_to    DATE,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT taxes_and_fees_valid_dates_chk CHECK (valid_to IS NULL OR valid_from <= valid_to)
);

CREATE INDEX idx_taxes_and_fees_active     ON taxes_and_fees (active);
CREATE INDEX idx_taxes_and_fees_valid_from ON taxes_and_fees (valid_from);
