-- =============================================================================
-- V6__reservation_evolution.sql
-- Hotel Manager -- Evolucion de reservaciones (ER-9, ER-13.5, ER-14, ER-16.5
-- de docs/hotel-rules.md §2-3). Dialecto: PostgreSQL 16. Ejecutado tras V5.
--
-- Crea:
--   * reservation_nightly_rates  (ER-9)    Snapshot inmutable por noche.
--   * reservation_adjustments    (ER-13.5, ER-16.5) Historial de modificaciones.
--   * reservation_groups         (ER-14)   Agrupacion de reservas (grupos).
--
-- Modifica:
--   * reservations: anade group_id (nullable, FK a reservation_groups ON DELETE
--     SET NULL) y cancellation_policy_id (nullable, FK se anade en V7).
--
-- Notas:
--   * reservation_nightly_rates.total se valida con CHECK aritmetico:
--     total = base_rate + extra_person_charge - discount_amount
--             + taxes_amount + fees_amount
--     Aritmetica NUMERIC(12,2) exacta (sin coma flotante).
--   * rate_plan_id en reservation_nightly_rates usa ON DELETE RESTRICT para
--     proteger el snapshot historico (no se puede borrar un plan referenciado
--     por una nightly rate confirmada).
--   * reservation_adjustments.metadata es JSONB libre para volcar antes/después
--     de cambios (fechas, habitacion, importes, etc.).
-- =============================================================================
-- reservation_nightly_rates  (ER-9)
--   Snapshot inmutable por noche. Una fila por noche entre checkIn y checkOut
--   (check_out exclusivo). Se crea al pasar la reserva de PENDING a CONFIRMED.
--   base_rate, extra_person_charge, discount_amount, taxes_amount, fees_amount
--   y total NO se modifican tras la creacion (ER-9 inmutabilidad). `included`
--   puede pasar a false al reducir estancia (auditoria), nunca a true de nuevo.
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_nightly_rates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    rate_plan_id        BIGINT NOT NULL REFERENCES rate_plans(id) ON DELETE RESTRICT,
    night_date          DATE NOT NULL,
    base_rate           NUMERIC(12,2) NOT NULL CHECK (base_rate >= 0),
    extra_person_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (extra_person_charge >= 0),
    discount_amount     NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    taxes_amount        NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (taxes_amount >= 0),
    fees_amount         NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (fees_amount >= 0),
    total               NUMERIC(12,2) NOT NULL,
    included            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservation_nightly_rates_total_chk CHECK (
        total = base_rate + extra_person_charge - discount_amount
                + taxes_amount + fees_amount
    )
);

CREATE INDEX idx_reservation_nightly_rates_reservation_id       ON reservation_nightly_rates (reservation_id);
CREATE INDEX idx_reservation_nightly_rates_night_date           ON reservation_nightly_rates (night_date);
CREATE INDEX idx_reservation_nightly_rates_reservation_included ON reservation_nightly_rates (reservation_id, included);

-- -----------------------------------------------------------------------------
-- reservation_adjustments  (ER-13.5, ER-16.5)
--   Historial de modificaciones a una reserva: EXTEND, REDUCE, CHANGE_DATES,
--   CHANGE_ROOM, CANCEL, NO_SHOW, PENALTY. old_value / new_value en TEXT (p.ej.
--   fechas ISO, room_id). metadata JSONB para volcado estructurado opcional.
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_adjustments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    adjustment_type TEXT NOT NULL CHECK (adjustment_type IN
        ('EXTEND', 'REDUCE', 'CHANGE_DATES', 'CHANGE_ROOM', 'CANCEL', 'NO_SHOW', 'PENALTY')),
    old_value       TEXT,
    new_value       TEXT,
    reason          TEXT,
    user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reservation_adjustments_reservation_id  ON reservation_adjustments (reservation_id);
CREATE INDEX idx_reservation_adjustments_adjustment_type ON reservation_adjustments (adjustment_type);

-- -----------------------------------------------------------------------------
-- reservation_groups  (ER-14)
--   Agrupacion de reservas (grupos). contact_guest_id es el huesped de contacto
--   principal (ON DELETE SET NULL: se conserva el grupo aunque se borre el
--   contacto). Cada reserva del grupo referencia group_id en reservations.
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_groups (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    contact_guest_id BIGINT REFERENCES guests(id) ON DELETE SET NULL,
    notes            TEXT,
    created_by       BIGINT REFERENCES users(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reservation_groups_contact_guest_id ON reservation_groups (contact_guest_id);

-- -----------------------------------------------------------------------------
-- Ampliaciones de reservations (compatibles hacia atras: columnas nullable).
--   * group_id: FK a reservation_groups ON DELETE SET NULL.
--   * cancellation_policy_id: nullable, FK se anade en V7 (la tabla
--     cancellation_policies no existe hasta V7).
-- -----------------------------------------------------------------------------
ALTER TABLE reservations
    ADD COLUMN group_id BIGINT REFERENCES reservation_groups(id) ON DELETE SET NULL,
    ADD COLUMN cancellation_policy_id BIGINT;

CREATE INDEX idx_reservations_group_id ON reservations (group_id);
