-- =============================================================================
-- V7__policies_and_blocks.sql
-- Hotel Manager -- Politicas de cancelacion y bloqueos operativos (ER-10,
-- ER-17 de docs/hotel-rules.md §3-4). Dialecto: PostgreSQL 16. Ejecutado tras V6.
--
-- Crea:
--   * cancellation_policies (ER-10) Politicas de cancelacion / no-show.
--   * room_blocks            (ER-17) Bloqueos operativos sin reserva.
--
-- Modifica:
--   * rate_plans:    anade FK cancellation_policy_id -> cancellation_policies
--     ON DELETE SET NULL.
--   * reservations:  anade FK cancellation_policy_id -> cancellation_policies
--     ON DELETE SET NULL.
--
-- Notas:
--   * room_blocks previene solapamiento por habitacion con EXCLUDE USING gist
--     sobre (room_id, overlap_range), patron identico a reservation_rooms (V1).
--     Requiere btree_gist (ya instalado en V1; se repite por seguridad).
--   * La exclusion GiST de room_blocks opera sobre TODAS las filas (incluidas
--     las released_at NOT NULL). El backend debe DELETE o actualizar las filas
--     liberadas antes de crear un bloqueo solapante, o ajustar la logica.
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -----------------------------------------------------------------------------
-- cancellation_policies  (ER-10)
--   Politica de cancelacion y no-show. deadline_hours = horas antes de checkIn
--   para cancelar sin penalizacion. penalty_type: NONE, PERCENTAGE, FIXED,
--   FIRST_NIGHT. penalty_value: porcentaje (si PERCENTAGE) o importe fijo.
-- -----------------------------------------------------------------------------
CREATE TABLE cancellation_policies (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT NOT NULL,
    deadline_hours         INT NOT NULL CHECK (deadline_hours >= 0),
    penalty_type           TEXT NOT NULL CHECK (penalty_type IN ('NONE', 'PERCENTAGE', 'FIXED', 'FIRST_NIGHT')),
    penalty_value          NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (penalty_value >= 0),
    no_show_penalty_type   TEXT NOT NULL CHECK (no_show_penalty_type IN ('NONE', 'PERCENTAGE', 'FIXED', 'FIRST_NIGHT')),
    no_show_penalty_value  NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (no_show_penalty_value >= 0),
    active                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cancellation_policies_active ON cancellation_policies (active);

-- FKs diferidas: rate_plans.cancellation_policy_id y
-- reservations.cancellation_policy_id se declararon como BIGINT nullable en V5
-- y V6 respectivamente. Ahora se anaden las FKs.
ALTER TABLE rate_plans
    ADD CONSTRAINT fk_rate_plans_cancellation_policy
    FOREIGN KEY (cancellation_policy_id)
    REFERENCES cancellation_policies(id) ON DELETE SET NULL;

ALTER TABLE reservations
    ADD CONSTRAINT fk_reservations_cancellation_policy
    FOREIGN KEY (cancellation_policy_id)
    REFERENCES cancellation_policies(id) ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- room_blocks  (ER-17)
--   Bloqueo operativo de una habitacion (MAINTENANCE, OPERATIONAL) para un
--   rango de fechas, sin reserva asociada. released_at nullable libera el
--   bloqueo (la habitacion vuelve a estar disponible si status = AVAILABLE).
--   Prevencion de solapamiento por habitacion: EXCLUDE USING gist sobre
--   (room_id, overlap_range), donde overlap_range es columna generada STORED
--   a partir de daterange(start_date, end_date, '[)') (patron V1).
-- -----------------------------------------------------------------------------
CREATE TABLE room_blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id       BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    block_type    TEXT NOT NULL CHECK (block_type IN ('MAINTENANCE', 'OPERATIONAL')),
    reason        TEXT,
    created_by    BIGINT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at   TIMESTAMPTZ,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(start_date, end_date, '[)')) STORED,
    CONSTRAINT room_blocks_end_gt_start_chk CHECK (end_date > start_date)
);

CREATE INDEX idx_room_blocks_room_id     ON room_blocks (room_id);
CREATE INDEX idx_room_blocks_start_date  ON room_blocks (start_date);
CREATE INDEX idx_room_blocks_block_type  ON room_blocks (block_type);
CREATE INDEX idx_room_blocks_released_at ON room_blocks (released_at);

ALTER TABLE room_blocks
    ADD CONSTRAINT room_blocks_no_overlap
    EXCLUDE USING gist (room_id WITH =, overlap_range WITH &&);
