-- =============================================================================
-- V8__housekeeping.sql
-- Hotel Manager -- Housekeeping (ER-18 de docs/hotel-rules.md §4).
-- Dialecto: PostgreSQL 16. Ejecutado por Flyway tras V7.
--
-- Modifica:
--   * rooms: anade housekeeping_status TEXT nullable con CHECK en
--     (DIRTY, CLEANING, INSPECTED, READY). Es el estado de limpieza actual,
--     SEPARADO de rooms.status (estado operativo AVAILABLE/RESERVED/...).
--     Nullable para no romper filas existentes (estados previos a V8 = NULL).
--
-- Crea:
--   * housekeeping_tasks (ER-18) Tareas de limpieza con estado, prioridad,
--     responsable, notas y marcas de creacion / actualizacion / completado.
--
-- Flujo (ER-18.2): DIRTY -> CLEANING -> INSPECTED -> READY
--   (al marcar READY, el backend pone rooms.status = AVAILABLE y
--   completed_at = now).
-- =============================================================================
-- rooms.housekeeping_status: estado de limpieza, independiente de status.
ALTER TABLE rooms
    ADD COLUMN housekeeping_status TEXT
    CHECK (housekeeping_status IS NULL OR
           housekeeping_status IN ('DIRTY', 'CLEANING', 'INSPECTED', 'READY'));

CREATE INDEX idx_rooms_housekeeping_status ON rooms (housekeeping_status);

-- -----------------------------------------------------------------------------
-- housekeeping_tasks  (ER-18)
--   Tarea de limpieza asignada a una habitacion. status (DIRTY, CLEANING,
--   INSPECTED, READY), priority (LOW, NORMAL, HIGH, URGENT), assigned_to
--   (usuario housekeeping, nullable), notes, completed_at (nullable, se setea
--   al llegar a READY). created_by = usuario que creo la tarea.
-- -----------------------------------------------------------------------------
CREATE TABLE housekeeping_tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    status       TEXT NOT NULL DEFAULT 'DIRTY'
                 CHECK (status IN ('DIRTY', 'CLEANING', 'INSPECTED', 'READY')),
    priority     TEXT NOT NULL DEFAULT 'NORMAL'
                 CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    assigned_to  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    created_by   BIGINT REFERENCES users(id)
);

CREATE INDEX idx_housekeeping_tasks_room_id     ON housekeeping_tasks (room_id);
CREATE INDEX idx_housekeeping_tasks_status      ON housekeeping_tasks (status);
CREATE INDEX idx_housekeeping_tasks_priority    ON housekeeping_tasks (priority);
CREATE INDEX idx_housekeeping_tasks_assigned_to ON housekeeping_tasks (assigned_to);
