-- =============================================================================
-- V9__privacy.sql
-- Hotel Manager -- Privacidad y nuevos roles (ER-25, ER-26 de
-- docs/hotel-rules.md §8; privacy-threat-model.md §4). Dialecto: PostgreSQL 16.
-- Ejecutado por Flyway tras V8.
--
-- Modifica:
--   * users: ampliar el CHECK de role para admitir HOUSEKEEPING, MANAGER y
--     PRIVACY_OFFICER (ademas de ADMIN, RECEPCIONISTA).
--   * guests: anade do_not_contact BOOLEAN NOT NULL DEFAULT FALSE.
--
-- Crea:
--   * privacy_requests          (ER-26) Solicitudes ARCO (EXPORT, RECTIFY,
--     DELETE) con estado y responsable.
--   * personal_data_access_logs (ER-25) Auditoria de acceso a datos personales
--     (VIEW, EXPORT, MODIFY, ANONYMIZE).
--
-- Notas:
--   * No se modifican V1-V4. El CHECK users_role_check se reemplaza aqui por
--     uno nuevo con la lista ampliada (DROP + ADD CONSTRAINT).
--   * do_not_contact es NOT NULL DEFAULT FALSE (las filas existentes de V2
--     reciben el valor por defecto al añadir la columna).
-- =============================================================================
-- users.role: ampliar enumeracion de roles. El nombre auto-generado por V1 es
-- users_role_check; se elimina y se anade uno nuevo con la lista ampliada.
ALTER TABLE users DROP CONSTRAINT users_role_check;

ALTER TABLE users
    ADD CONSTRAINT users_role_check
    CHECK (role IN ('ADMIN', 'RECEPCIONISTA', 'HOUSEKEEPING', 'MANAGER', 'PRIVACY_OFFICER'));

-- -----------------------------------------------------------------------------
-- privacy_requests  (ER-26)
--   Solicitud de privacidad (ARCO): EXPORT, RECTIFY, DELETE. Estado: PENDING,
--   IN_PROGRESS, COMPLETED, REJECTED. handled_by = usuario que procesa
--   (PRIVACY_OFFICER). guest_id ON DELETE RESTRICT: no se puede borrar un
--   huesped con solicitud abierta (preserva trazabilidad).
-- -----------------------------------------------------------------------------
CREATE TABLE privacy_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id     BIGINT NOT NULL REFERENCES guests(id) ON DELETE RESTRICT,
    type         TEXT NOT NULL CHECK (type IN ('EXPORT', 'RECTIFY', 'DELETE')),
    status       TEXT NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    handled_by   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_privacy_requests_guest_id ON privacy_requests (guest_id);
CREATE INDEX idx_privacy_requests_status   ON privacy_requests (status);
CREATE INDEX idx_privacy_requests_type     ON privacy_requests (type);

-- -----------------------------------------------------------------------------
-- personal_data_access_logs  (ER-25)
--   Auditoria de acceso a datos personales no enmascarados. action: VIEW,
--   EXPORT, MODIFY, ANONYMIZE. user_id y guest_id ON DELETE SET NULL: se
--   conserva el log aunque se borre el usuario o el huesped (anonimizacion
--   preserva guest_id, asi que normalmente no se borra).
-- -----------------------------------------------------------------------------
CREATE TABLE personal_data_access_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    guest_id      BIGINT REFERENCES guests(id) ON DELETE SET NULL,
    action        TEXT NOT NULL CHECK (action IN ('VIEW', 'EXPORT', 'MODIFY', 'ANONYMIZE')),
    justification TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_personal_data_access_logs_guest_id   ON personal_data_access_logs (guest_id);
CREATE INDEX idx_personal_data_access_logs_user_id    ON personal_data_access_logs (user_id);
CREATE INDEX idx_personal_data_access_logs_action     ON personal_data_access_logs (action);
CREATE INDEX idx_personal_data_access_logs_created_at ON personal_data_access_logs (created_at);

-- -----------------------------------------------------------------------------
-- guests.do_not_contact: bandera de exclusion de comunicaciones (resultado de
-- una solicitud de privacidad RECTIFY/DELETE parcial o preferencia del huesped).
-- -----------------------------------------------------------------------------
ALTER TABLE guests
    ADD COLUMN do_not_contact BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_guests_do_not_contact ON guests (do_not_contact);
