import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { spawnSync } from 'node:child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const frontendDir = join(__dirname, '..')
const outDir = join(frontendDir, 'src', 'api', 'generated')
const outPath = join(outDir, 'schema.ts')
const rawPath = join(outDir, 'schema.raw.ts')
const localSnapshot = join(__dirname, 'openapi.snapshot.json')

function generateFrom(source, label) {
  const bin = join(frontendDir, 'node_modules', 'openapi-typescript', 'bin', 'cli.js')
  const args = [bin, source, '-o', rawPath]
  console.log(`[api:generate] generating from ${label}`)
  const res = spawnSync(process.execPath, args, { stdio: 'inherit', shell: false })
  return res.status === 0
}

async function loadOpenApi(source) {
  if (source.startsWith('http://') || source.startsWith('https://')) {
    const res = await fetch(source)
    if (!res.ok) {
      throw new Error(`OpenAPI fetch failed with status ${res.status}`)
    }
    return res.json()
  }

  return JSON.parse(readFileSync(source, 'utf8'))
}

function writeCompatibilityWrapper(openApi) {
  const pathKeys = Object.keys(openApi.paths ?? {}).sort()
  const aliases = [
    ['AssignRoomDto', 'AssignRoomRequest', 'request'],
    ['AuthResponse', 'AuthResponse', 'response'],
    ['AvailabilityRoomDto', 'AvailabilityRoomDto', 'response'],
    ['CancellationPolicyCreateDto', 'CancellationPolicyCreateRequest', 'request'],
    ['CancellationPolicyDto', 'CancellationPolicyDto', 'response'],
    ['ChangeRoomDto', 'ChangeRoomRequest', 'request'],
    ['CheckInDto', 'CheckInRequest', 'request'],
    ['DailyRateOverrideCreateDto', 'DailyRateOverrideCreateRequest', 'request'],
    ['DailyRateOverrideDto', 'DailyRateOverrideDto', 'response'],
    ['DashboardDto', 'DashboardDto', 'response'],
    ['GuestDto', 'GuestDto', 'response'],
    ['GuestFullDto', 'GuestFullDto', 'response'],
    ['GuestFullExportDto', 'GuestFullExportDto', 'response'],
    ['GuestWriteDto', 'GuestCreateRequest', 'request'],
    ['HousekeepingStatusUpdateDto', 'HousekeepingStatusUpdateRequest', 'request'],
    ['HousekeepingTaskCreateDto', 'HousekeepingTaskCreateRequest', 'request'],
    ['HousekeepingTaskDto', 'HousekeepingTaskDto', 'response'],
    ['ModifyStayDto', 'ModifyStayRequest', 'request'],
    ['NoShowDto', 'NoShowRequest', 'request'],
    ['PaymentCreateDto', 'PaymentCreateRequest', 'request'],
    ['PaymentDto', 'PaymentDto', 'response'],
    ['PaymentStatusDto', 'PaymentStatusRequest', 'request'],
    ['PersonalDataAccessLogDto', 'PersonalDataAccessLogDto', 'response'],
    ['PrivacyRequestCreateDto', 'PrivacyRequestCreateRequest', 'request'],
    ['PrivacyRequestDto', 'PrivacyRequestDto', 'response'],
    ['PrivacyRequestUpdateDto', 'PrivacyRequestUpdateRequest', 'request'],
    ['PromotionRuleCreateDto', 'PromotionRuleCreateRequest', 'request'],
    ['PromotionRuleDto', 'PromotionRuleDto', 'response'],
    ['QuoteNightlyRateDto', 'QuoteNightlyRateDto', 'response'],
    ['QuoteRequest', 'QuoteRequest', 'request'],
    ['QuoteResultDto', 'QuoteResultDto', 'response'],
    ['RatePlanCreateDto', 'RatePlanCreateRequest', 'request'],
    ['RatePlanDto', 'RatePlanDto', 'response'],
    ['RatePlanStatusDto', 'RatePlanStatusRequest', 'request'],
    ['ReservationAdjustmentDto', 'ReservationAdjustmentDto', 'response'],
    ['ReservationCreateDto', 'ReservationCreateRequest', 'request'],
    ['ReservationDto', 'ReservationDto', 'response'],
    ['ReservationGroupCreateDto', 'ReservationGroupCreateRequest', 'request'],
    ['ReservationGroupDto', 'ReservationGroupDto', 'response'],
    ['ReservationNightlyRateDto', 'ReservationNightlyRateDto', 'response'],
    ['ReservationUpdateDto', 'ReservationUpdateRequest', 'request'],
    ['RoomBlockCreateDto', 'RoomBlockCreateRequest', 'request'],
    ['RoomBlockDto', 'RoomBlockDto', 'response'],
    ['RoomDto', 'RoomDto', 'response'],
    ['RoomObservationsDto', 'RoomObservationsRequest', 'request'],
    ['RoomStatusDto', 'RoomStatusUpdateRequest', 'request'],
    ['RoomTypeDto', 'RoomTypeDto', 'response'],
    ['RoomTypeWriteDto', 'RoomTypeCreateRequest', 'request'],
    ['RoomWriteDto', 'RoomCreateRequest', 'request'],
    ['SeasonalRateCreateDto', 'SeasonalRateCreateRequest', 'request'],
    ['SeasonalRateDto', 'SeasonalRateDto', 'response'],
    ['StatusDto', 'UserStatusRequest', 'request'],
    ['TaxOrFeeCreateDto', 'TaxOrFeeCreateRequest', 'request'],
    ['TaxOrFeeDto', 'TaxOrFeeDto', 'response'],
    ['UserDto', 'UserDto', 'response'],
    ['UserWriteDto', 'UserCreateRequest', 'request'],
  ]

  const lines = [
    '/*',
    ' * This file is auto-generated by scripts/generate-api.mjs.',
    ' * Do not edit directly. The raw openapi-typescript output lives in schema.raw.ts.',
    ' */',
    "import type { paths as RawPaths, components as RawComponents, operations as RawOperations } from './schema.raw'",
    '',
    'type Schemas = RawComponents["schemas"]',
    'type ResponseDto<T> = T extends Array<infer U>',
    '  ? ResponseDto<U>[]',
    '  : T extends object',
    '    ? { [K in keyof T]-?: ResponseDto<NonNullable<T[K]>> }',
    '    : NonNullable<T>',
    'type RequestDto<T> = T extends Array<infer U>',
    '  ? RequestDto<U>[]',
    '  : T extends object',
    '    ? { [K in keyof T]: RequestDto<T[K]> | null }',
    '    : T | null',
    '',
    'export type paths = RawPaths',
    'export type components = RawComponents',
    'export type operations = RawOperations',
    '',
    `export const PATHS = ${JSON.stringify(pathKeys, null, 2)} as const`,
    'export type ApiPath = (typeof PATHS)[number]',
    '',
    'export type PageDto<T> = {',
    '  content: T[]',
    '  page: number',
    '  size: number',
    '  totalElements: number',
    '  totalPages: number',
    '}',
    '',
    ...aliases.map(([alias, source, kind]) => (
      `export type ${alias} = ${kind === 'request' ? 'RequestDto' : 'ResponseDto'}<Schemas["${source}"]>`
    )),
    '',
    'export type HousekeepingStatus = NonNullable<HousekeepingTaskDto["status"]>',
    'export type HousekeepingPriority = NonNullable<HousekeepingTaskDto["priority"]>',
    'export type SeasonType = NonNullable<SeasonalRateDto["seasonType"]>',
    'export type PriceMode = NonNullable<SeasonalRateDto["priceMode"]>',
    'export type TaxType = NonNullable<TaxOrFeeDto["type"]>',
    'export type TaxAppliesTo = NonNullable<TaxOrFeeDto["appliesTo"]>',
    'export type DiscountType = NonNullable<PromotionRuleDto["discountType"]>',
    'export type PenaltyType = NonNullable<CancellationPolicyDto["penaltyType"]>',
    'export type BlockType = NonNullable<RoomBlockDto["blockType"]>',
    'export type AdjustmentType = NonNullable<ReservationAdjustmentDto["adjustmentType"]>',
    'export type PrivacyRequestType = NonNullable<PrivacyRequestDto["type"]>',
    'export type PrivacyRequestStatus = NonNullable<PrivacyRequestDto["status"]>',
    'export type DataAccessAction = NonNullable<PersonalDataAccessLogDto["action"]>',
  ]

  writeFileSync(outPath, `${lines.join('\n')}\n`)
}

function generateFromSnapshot() {
  if (!existsSync(localSnapshot)) return false
  const ok = generateFrom(localSnapshot, 'snapshot')
  if (ok) {
    writeCompatibilityWrapper(JSON.parse(readFileSync(localSnapshot, 'utf8')))
  }
  return ok
}

async function generateFromLiveBackend(source) {
  const openApi = await loadOpenApi(source)
  const ok = generateFrom(source, 'live backend')
  if (ok) {
    writeCompatibilityWrapper(openApi)
  }
  return ok
}

async function backendReachable(url) {
  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 4000)
    const res = await fetch(url, { signal: controller.signal })
    clearTimeout(timeout)
    return res.ok
  } catch {
    return false
  }
}

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

let ok = false
const liveSchema = 'http://localhost:8080/api/openapi.json'

if (await backendReachable(liveSchema)) {
  ok = await generateFromLiveBackend(liveSchema)
}

if (!ok) {
  console.log('[api:generate] Backend not reachable. Falling back to local snapshot.')
  ok = generateFromSnapshot()
}

if (!ok) {
  console.log('[api:generate] No snapshot found. Keeping existing src/api/generated/schema.ts (manually authored).')
  if (!existsSync(outPath)) {
    writeFileSync(outPath, '// placeholder - generated by npm run api:generate\n')
  }
}

console.log(`[api:generate] done -> ${outPath}`)
