-- =============================================================================
-- database/schema.sql  -- COPIA DE REFERENCIA (NO la ejecuta Flyway).
-- Esquema completo equivalente a la union de las migraciones Flyway de
-- backend/src/main/resources/db/migration/ (V1 + estado tras V2).
-- Para crear la BD desde cero con este archivo:
--     psql -U hotel -d hotelmanager -f database/schema.sql
--     psql -U hotel -d hotelmanager -f database/seed.sql
-- En el proyecto real, Flyway aplica las migraciones de backend/ al arrancar
-- Spring Boot; este archivo existe solo para documentacion / inspeccion rapida.
-- Dialecto: PostgreSQL 16.
-- =============================================================================

-- Extensión requerida por EXCLUDE USING gist de reservation_rooms ('=' sobre
-- BIGINT). En dev (postgres:16-alpine) POSTGRES_USER es superusuario.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name     TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('ADMIN', 'RECEPCIONISTA')),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- guests
-- -----------------------------------------------------------------------------
CREATE TABLE guests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      TEXT NOT NULL,
    last_name       TEXT NOT NULL,
    email           TEXT,
    phone           TEXT,
    document_number TEXT NOT NULL,
    nationality     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_guests_document_number ON guests (document_number);
CREATE INDEX idx_guests_email_lower     ON guests (lower(email));
CREATE INDEX idx_guests_name_lower      ON guests (lower(first_name), lower(last_name));

-- -----------------------------------------------------------------------------
-- room_types
-- -----------------------------------------------------------------------------
CREATE TABLE room_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT,
    max_capacity INT NOT NULL CHECK (max_capacity > 0),
    base_price   NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
    amenities    JSONB NOT NULL DEFAULT '[]'::jsonb,
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- rooms
-- -----------------------------------------------------------------------------
CREATE TABLE rooms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number       TEXT NOT NULL UNIQUE,
    floor        INT NOT NULL,
    room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    status       TEXT NOT NULL DEFAULT 'AVAILABLE'
                 CHECK (status IN ('AVAILABLE', 'RESERVED', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', 'OUT_OF_SERVICE')),
    observations TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_rooms_status       ON rooms (status);
CREATE INDEX idx_rooms_floor        ON rooms (floor);
CREATE INDEX idx_rooms_room_type_id ON rooms (room_type_id);

-- -----------------------------------------------------------------------------
-- reservations
-- -----------------------------------------------------------------------------
CREATE TABLE reservations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id         BIGINT NOT NULL REFERENCES guests(id) ON DELETE RESTRICT,
    status           TEXT NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW')),
    check_in         DATE NOT NULL,
    check_out        DATE NOT NULL,
    adults           INT NOT NULL CHECK (adults >= 0),
    children         INT NOT NULL CHECK (children >= 0),
    room_type_id     BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    nightly_price    NUMERIC(12,2) NOT NULL,
    total_amount     NUMERIC(12,2) NOT NULL,
    notes            TEXT,
    special_requests TEXT,
    check_in_at      TIMESTAMPTZ,
    check_out_at     TIMESTAMPTZ,
    checked_in_by    BIGINT REFERENCES users(id),
    checked_out_by   BIGINT REFERENCES users(id),
    cancelled_at     TIMESTAMPTZ,
    cancelled_by     BIGINT REFERENCES users(id),
    created_by       BIGINT REFERENCES users(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservations_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_reservations_status    ON reservations (status);
CREATE INDEX idx_reservations_check_in  ON reservations (check_in);
CREATE INDEX idx_reservations_check_out ON reservations (check_out);
CREATE INDEX idx_reservations_guest_id  ON reservations (guest_id);

-- -----------------------------------------------------------------------------
-- reservation_rooms  (asignacion de habitacion a reserva para un rango)
-- Prevencion de solapamiento: columna generada + EXCLUDE USING gist.
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    room_id       BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    check_in      DATE NOT NULL,
    check_out     DATE NOT NULL,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(check_in, check_out, '[)')) STORED,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservation_rooms_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_reservation_rooms_reservation_id ON reservation_rooms (reservation_id);
CREATE INDEX idx_reservation_rooms_room_id        ON reservation_rooms (room_id);

ALTER TABLE reservation_rooms
    ADD CONSTRAINT reservation_rooms_no_overlap
    EXCLUDE USING gist (room_id WITH =, overlap_range WITH &&);

-- -----------------------------------------------------------------------------
-- payments
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    amount        NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    method        TEXT NOT NULL CHECK (method IN ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER')),
    status        TEXT NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED')),
    reference     TEXT,
    paid_at       TIMESTAMPTZ,
    created_by    BIGINT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_reservation_id ON payments (reservation_id);

-- -----------------------------------------------------------------------------
-- audit_events
-- -----------------------------------------------------------------------------
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action      TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id   BIGINT,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_events_entity     ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_events_created_at ON audit_events (created_at);
