-- =============================================================================
-- database/schema.sql  -- COPIA DE REFERENCIA (NO la ejecuta Flyway).
-- Esquema completo equivalente a la union de las migraciones Flyway de
-- backend/src/main/resources/db/migration/ (V1 + V3; V2 y V4 son solo datos).
-- Para crear la BD desde cero con este archivo:
--     psql -U hotel -d hotelmanager -f database/schema.sql
--     psql -U hotel -d hotelmanager -f database/seed.sql
-- En el proyecto real, Flyway aplica las migraciones de backend/ al arrancar
-- Spring Boot; este archivo existe solo para documentacion / inspeccion rapida.
-- Dialecto: PostgreSQL 16.
--
-- Estado reflejado:
--   V1__init_schema.sql         -> tablas base (users, guests, room_types,
--                                  rooms, reservations, reservation_rooms,
--                                  payments, audit_events) + EXCLUDE GiST.
--   V3__refresh_tokens.sql      -> tabla refresh_tokens + indices (auth).
--   (V2 y V4 son migraciones de datos; ver database/seed.sql.)
-- =============================================================================

-- Extensión requerida por EXCLUDE USING gist de reservation_rooms ('=' sobre
-- BIGINT). En dev (postgres:16-alpine) POSTGRES_USER es superusuario.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name     TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('ADMIN', 'RECEPCIONISTA')),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- guests
-- -----------------------------------------------------------------------------
CREATE TABLE guests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      TEXT NOT NULL,
    last_name       TEXT NOT NULL,
    email           TEXT,
    phone           TEXT,
    document_number TEXT NOT NULL,
    nationality     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_guests_document_number ON guests (document_number);
CREATE INDEX idx_guests_email_lower     ON guests (lower(email));
CREATE INDEX idx_guests_name_lower      ON guests (lower(first_name), lower(last_name));

-- -----------------------------------------------------------------------------
-- room_types
-- -----------------------------------------------------------------------------
CREATE TABLE room_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT,
    max_capacity INT NOT NULL CHECK (max_capacity > 0),
    base_price   NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
    amenities    JSONB NOT NULL DEFAULT '[]'::jsonb,
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- rooms
-- -----------------------------------------------------------------------------
CREATE TABLE rooms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number       TEXT NOT NULL UNIQUE,
    floor        INT NOT NULL,
    room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    status       TEXT NOT NULL DEFAULT 'AVAILABLE'
                 CHECK (status IN ('AVAILABLE', 'RESERVED', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', 'OUT_OF_SERVICE')),
    observations TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_rooms_status       ON rooms (status);
CREATE INDEX idx_rooms_floor        ON rooms (floor);
CREATE INDEX idx_rooms_room_type_id ON rooms (room_type_id);

-- -----------------------------------------------------------------------------
-- reservations
-- -----------------------------------------------------------------------------
CREATE TABLE reservations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id         BIGINT NOT NULL REFERENCES guests(id) ON DELETE RESTRICT,
    status           TEXT NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW')),
    check_in         DATE NOT NULL,
    check_out        DATE NOT NULL,
    adults           INT NOT NULL CHECK (adults >= 0),
    children         INT NOT NULL CHECK (children >= 0),
    room_type_id     BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    nightly_price    NUMERIC(12,2) NOT NULL,
    total_amount     NUMERIC(12,2) NOT NULL,
    notes            TEXT,
    special_requests TEXT,
    check_in_at      TIMESTAMPTZ,
    check_out_at     TIMESTAMPTZ,
    checked_in_by    BIGINT REFERENCES users(id),
    checked_out_by   BIGINT REFERENCES users(id),
    cancelled_at     TIMESTAMPTZ,
    cancelled_by     BIGINT REFERENCES users(id),
    created_by       BIGINT REFERENCES users(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservations_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_reservations_status    ON reservations (status);
CREATE INDEX idx_reservations_check_in  ON reservations (check_in);
CREATE INDEX idx_reservations_check_out ON reservations (check_out);
CREATE INDEX idx_reservations_guest_id  ON reservations (guest_id);

-- -----------------------------------------------------------------------------
-- reservation_rooms  (asignacion de habitacion a reserva para un rango)
-- Prevencion de solapamiento: columna generada + EXCLUDE USING gist.
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    room_id       BIGINT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
    check_in      DATE NOT NULL,
    check_out     DATE NOT NULL,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(check_in, check_out, '[)')) STORED,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservation_rooms_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_reservation_rooms_reservation_id ON reservation_rooms (reservation_id);
CREATE INDEX idx_reservation_rooms_room_id        ON reservation_rooms (room_id);

ALTER TABLE reservation_rooms
    ADD CONSTRAINT reservation_rooms_no_overlap
    EXCLUDE USING gist (room_id WITH =, overlap_range WITH &&);

-- -----------------------------------------------------------------------------
-- payments
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    amount        NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    method        TEXT NOT NULL CHECK (method IN ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'ADJUSTMENT')),
    status        TEXT NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED')),
    reference     TEXT,
    paid_at       TIMESTAMPTZ,
    created_by    BIGINT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_reservation_id ON payments (reservation_id);

-- -----------------------------------------------------------------------------
-- audit_events
-- -----------------------------------------------------------------------------
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action      TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id   BIGINT,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_events_entity     ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_events_created_at ON audit_events (created_at);

-- -----------------------------------------------------------------------------
-- refresh_tokens  (V3__refresh_tokens.sql)
-- Persistencia de refresh tokens para el flujo de auth con rotacion.
--   * token_hash: SHA-256 del token (nunca el token original).
--   * jti:        JWT ID unico del token emitido.
--   * revoked_at: NULL = activo; fecha = revocado (rotacion o logout).
--   * replaced_by_jti: jti del token que lo reemplazo al rotar.
--   * device_info: User-Agent / info de sesion (opcional).
--   * CHECK (expires_at > created_at): el token nace valido.
-- Deteccion de reutilizacion: si se presenta un token ya revocado, el backend
-- revoca la cadena y devuelve 401. Ver docs/database.md seccion 9.
-- -----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    jti             TEXT NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    replaced_by_jti TEXT,
    device_info     TEXT,
    CONSTRAINT refresh_tokens_check_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_jti        ON refresh_tokens (jti);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- =============================================================================
-- Migraciones V5-V10 (schema). V11 es solo datos; ver database/seed.sql.
-- Las tablas siguientes se anaden sobre el esquema V1+V3. Las FKs a
-- cancellation_policies se declaran en V7 (la tabla se crea en V7).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist; -- repetida en V5/V7 por seguridad

-- -----------------------------------------------------------------------------
-- rate_plans  (V5, ER-1)
-- -----------------------------------------------------------------------------
CREATE TABLE rate_plans (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   TEXT NOT NULL UNIQUE,
    name                   TEXT NOT NULL,
    room_type_id           BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    weekday_rates          JSONB NOT NULL,
    adult_extra_rate       NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (adult_extra_rate >= 0),
    child_extra_rate       NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (child_extra_rate >= 0),
    cancellation_policy_id BIGINT,  -- FK anadida en V7
    min_nights             INT NOT NULL DEFAULT 1 CHECK (min_nights >= 1),
    max_nights             INT,
    is_default             BOOLEAN NOT NULL DEFAULT FALSE,
    active                 BOOLEAN NOT NULL DEFAULT TRUE,
    valid_from             DATE,
    valid_to               DATE,
    version                BIGINT NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rate_plans_max_nights_chk    CHECK (max_nights IS NULL OR max_nights > min_nights),
    CONSTRAINT rate_plans_valid_dates_chk   CHECK (valid_to IS NULL OR valid_from <= valid_to),
    CONSTRAINT rate_plans_weekday_rates_chk CHECK (
        jsonb_typeof(weekday_rates) = 'array'
        AND jsonb_array_length(weekday_rates) = 7
        AND NOT jsonb_path_exists(weekday_rates, '$[*] ? (@.type() != "number")')
        AND NOT jsonb_path_exists(weekday_rates, '$[*] ? (@.type() == "number" && @ < 0)')
    )
);

CREATE INDEX idx_rate_plans_room_type_id ON rate_plans (room_type_id);
CREATE INDEX idx_rate_plans_active       ON rate_plans (active);

-- -----------------------------------------------------------------------------
-- seasonal_rates  (V5, ER-2)  -- EXCLUDE GiST por (rate_plan_id, overlap_range)
-- -----------------------------------------------------------------------------
CREATE TABLE seasonal_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_plan_id  BIGINT NOT NULL REFERENCES rate_plans(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    season_type   TEXT NOT NULL CHECK (season_type IN ('ALTA', 'MEDIA', 'BAJA')),
    price_mode    TEXT NOT NULL CHECK (price_mode IN ('MULTIPLIER', 'ABSOLUTE')),
    weekdays      JSONB NOT NULL,
    version       BIGINT NOT NULL DEFAULT 0,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(start_date, end_date, '[)')) STORED,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT seasonal_rates_end_gt_start_chk CHECK (end_date > start_date),
    CONSTRAINT seasonal_rates_weekdays_chk CHECK (
        jsonb_typeof(weekdays) = 'array'
        AND jsonb_array_length(weekdays) = 7
        AND NOT jsonb_path_exists(weekdays, '$[*] ? (@.type() != "number")')
        AND NOT jsonb_path_exists(weekdays, '$[*] ? (@.type() == "number" && @ < 0)')
    )
);

CREATE INDEX idx_seasonal_rates_rate_plan_id ON seasonal_rates (rate_plan_id);
CREATE INDEX idx_seasonal_rates_start_date   ON seasonal_rates (start_date);
CREATE INDEX idx_seasonal_rates_end_date     ON seasonal_rates (end_date);

ALTER TABLE seasonal_rates
    ADD CONSTRAINT seasonal_rates_no_overlap
    EXCLUDE USING gist (rate_plan_id WITH =, overlap_range WITH &&);

-- -----------------------------------------------------------------------------
-- daily_rate_overrides  (V5, ER-3)
-- -----------------------------------------------------------------------------
CREATE TABLE daily_rate_overrides (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE RESTRICT,
    rate_plan_id BIGINT REFERENCES rate_plans(id) ON DELETE CASCADE,
    date         DATE NOT NULL,
    price        NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    reason       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (room_type_id, rate_plan_id, date)
);

CREATE INDEX idx_daily_rate_overrides_date         ON daily_rate_overrides (date);
CREATE INDEX idx_daily_rate_overrides_room_type_id ON daily_rate_overrides (room_type_id);

-- -----------------------------------------------------------------------------
-- promotion_rules  (V5, ER-4)
-- -----------------------------------------------------------------------------
CREATE TABLE promotion_rules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           TEXT NOT NULL UNIQUE,
    description    TEXT,
    discount_type  TEXT NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FIXED')),
    discount_value NUMERIC(12,2) NOT NULL CHECK (discount_value >= 0),
    min_nights     INT NOT NULL DEFAULT 1 CHECK (min_nights >= 1),
    min_guests     INT NOT NULL DEFAULT 1 CHECK (min_guests >= 1),
    valid_from     DATE,
    valid_to       DATE,
    rate_plan_id   BIGINT REFERENCES rate_plans(id) ON DELETE CASCADE,
    stackable      BOOLEAN NOT NULL DEFAULT FALSE,
    priority       INT NOT NULL DEFAULT 0,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT promotion_rules_pct_chk        CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100),
    CONSTRAINT promotion_rules_valid_dates_chk CHECK (valid_to IS NULL OR valid_from <= valid_to)
);

CREATE INDEX idx_promotion_rules_active     ON promotion_rules (active);
CREATE INDEX idx_promotion_rules_valid_from ON promotion_rules (valid_from);

-- -----------------------------------------------------------------------------
-- closed_dates  (V5, ER-6.2)
-- -----------------------------------------------------------------------------
CREATE TABLE closed_dates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id     BIGINT REFERENCES room_types(id) ON DELETE CASCADE,
    date             DATE NOT NULL,
    closed_arrival   BOOLEAN NOT NULL DEFAULT FALSE,
    closed_departure BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE NULLS NOT DISTINCT (room_type_id, date)
);

CREATE INDEX idx_closed_dates_date ON closed_dates (date);

-- -----------------------------------------------------------------------------
-- taxes_and_fees  (V5, ER-5)
-- -----------------------------------------------------------------------------
CREATE TABLE taxes_and_fees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    type        TEXT NOT NULL CHECK (type IN ('TAX_PERCENT', 'FEE_FIXED')),
    rate_value  NUMERIC(12,2) NOT NULL CHECK (rate_value >= 0),
    applies_to  TEXT NOT NULL CHECK (applies_to IN ('ROOM_RATE', 'TOTAL', 'PER_NIGHT')),
    valid_from  DATE,
    valid_to    DATE,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT taxes_and_fees_valid_dates_chk CHECK (valid_to IS NULL OR valid_from <= valid_to)
);

CREATE INDEX idx_taxes_and_fees_active     ON taxes_and_fees (active);
CREATE INDEX idx_taxes_and_fees_valid_from ON taxes_and_fees (valid_from);

-- -----------------------------------------------------------------------------
-- reservation_nightly_rates  (V6, ER-9)  -- snapshot inmutable por noche
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_nightly_rates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    rate_plan_id        BIGINT NOT NULL REFERENCES rate_plans(id) ON DELETE RESTRICT,
    night_date          DATE NOT NULL,
    base_rate           NUMERIC(12,2) NOT NULL CHECK (base_rate >= 0),
    extra_person_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (extra_person_charge >= 0),
    discount_amount     NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    taxes_amount        NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (taxes_amount >= 0),
    fees_amount         NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (fees_amount >= 0),
    total               NUMERIC(12,2) NOT NULL,
    included            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT reservation_nightly_rates_total_chk CHECK (
        total = base_rate + extra_person_charge - discount_amount + taxes_amount + fees_amount
    )
);

CREATE INDEX idx_reservation_nightly_rates_reservation_id       ON reservation_nightly_rates (reservation_id);
CREATE INDEX idx_reservation_nightly_rates_night_date           ON reservation_nightly_rates (night_date);
CREATE INDEX idx_reservation_nightly_rates_reservation_included ON reservation_nightly_rates (reservation_id, included);

-- -----------------------------------------------------------------------------
-- reservation_adjustments  (V6, ER-13.5 / ER-16.5)
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_adjustments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    adjustment_type TEXT NOT NULL CHECK (adjustment_type IN
        ('EXTEND', 'REDUCE', 'CHANGE_DATES', 'CHANGE_ROOM', 'CANCEL', 'NO_SHOW', 'PENALTY')),
    old_value       TEXT,
    new_value       TEXT,
    reason          TEXT,
    user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reservation_adjustments_reservation_id  ON reservation_adjustments (reservation_id);
CREATE INDEX idx_reservation_adjustments_adjustment_type ON reservation_adjustments (adjustment_type);

-- -----------------------------------------------------------------------------
-- reservation_groups  (V6, ER-14)
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_groups (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    contact_guest_id BIGINT REFERENCES guests(id) ON DELETE SET NULL,
    notes            TEXT,
    created_by       BIGINT REFERENCES users(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_reservation_groups_contact_guest_id ON reservation_groups (contact_guest_id);

-- Ampliaciones de reservations (V6): group_id + cancellation_policy_id (FK en V7)
ALTER TABLE reservations
    ADD COLUMN group_id BIGINT REFERENCES reservation_groups(id) ON DELETE SET NULL,
    ADD COLUMN cancellation_policy_id BIGINT;

CREATE INDEX idx_reservations_group_id ON reservations (group_id);

-- -----------------------------------------------------------------------------
-- cancellation_policies  (V7, ER-10)
-- -----------------------------------------------------------------------------
CREATE TABLE cancellation_policies (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   TEXT NOT NULL,
    deadline_hours         INT NOT NULL CHECK (deadline_hours >= 0),
    penalty_type           TEXT NOT NULL CHECK (penalty_type IN ('NONE', 'PERCENTAGE', 'FIXED', 'FIRST_NIGHT')),
    penalty_value          NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (penalty_value >= 0),
    no_show_penalty_type   TEXT NOT NULL CHECK (no_show_penalty_type IN ('NONE', 'PERCENTAGE', 'FIXED', 'FIRST_NIGHT')),
    no_show_penalty_value  NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (no_show_penalty_value >= 0),
    active                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cancellation_policies_active ON cancellation_policies (active);

ALTER TABLE rate_plans
    ADD CONSTRAINT fk_rate_plans_cancellation_policy
    FOREIGN KEY (cancellation_policy_id)
    REFERENCES cancellation_policies(id) ON DELETE SET NULL;

ALTER TABLE reservations
    ADD CONSTRAINT fk_reservations_cancellation_policy
    FOREIGN KEY (cancellation_policy_id)
    REFERENCES cancellation_policies(id) ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- room_blocks  (V7, ER-17)  -- EXCLUDE GiST por (room_id, overlap_range)
-- -----------------------------------------------------------------------------
CREATE TABLE room_blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id       BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    block_type    TEXT NOT NULL CHECK (block_type IN ('MAINTENANCE', 'OPERATIONAL')),
    reason        TEXT,
    created_by    BIGINT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at   TIMESTAMPTZ,
    overlap_range daterange NOT NULL
                  GENERATED ALWAYS AS (daterange(start_date, end_date, '[)')) STORED,
    CONSTRAINT room_blocks_end_gt_start_chk CHECK (end_date > start_date)
);

CREATE INDEX idx_room_blocks_room_id     ON room_blocks (room_id);
CREATE INDEX idx_room_blocks_start_date  ON room_blocks (start_date);
CREATE INDEX idx_room_blocks_block_type  ON room_blocks (block_type);
CREATE INDEX idx_room_blocks_released_at ON room_blocks (released_at);

ALTER TABLE room_blocks
    ADD CONSTRAINT room_blocks_no_overlap
    EXCLUDE USING gist (room_id WITH =, overlap_range WITH &&);

-- -----------------------------------------------------------------------------
-- housekeeping  (V8, ER-18)
-- -----------------------------------------------------------------------------
ALTER TABLE rooms
    ADD COLUMN housekeeping_status TEXT
    CHECK (housekeeping_status IS NULL OR
           housekeeping_status IN ('DIRTY', 'CLEANING', 'INSPECTED', 'READY'));

CREATE INDEX idx_rooms_housekeeping_status ON rooms (housekeeping_status);

CREATE TABLE housekeeping_tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    status       TEXT NOT NULL DEFAULT 'DIRTY'
                 CHECK (status IN ('DIRTY', 'CLEANING', 'INSPECTED', 'READY')),
    priority     TEXT NOT NULL DEFAULT 'NORMAL'
                 CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    assigned_to  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    created_by   BIGINT REFERENCES users(id)
);

CREATE INDEX idx_housekeeping_tasks_room_id     ON housekeeping_tasks (room_id);
CREATE INDEX idx_housekeeping_tasks_status      ON housekeeping_tasks (status);
CREATE INDEX idx_housekeeping_tasks_priority    ON housekeeping_tasks (priority);
CREATE INDEX idx_housekeeping_tasks_assigned_to ON housekeeping_tasks (assigned_to);

-- -----------------------------------------------------------------------------
-- privacy  (V9, ER-25 / ER-26)
-- -----------------------------------------------------------------------------
ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users
    ADD CONSTRAINT users_role_check
    CHECK (role IN ('ADMIN', 'RECEPCIONISTA', 'HOUSEKEEPING', 'MANAGER', 'PRIVACY_OFFICER'));

CREATE TABLE privacy_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id     BIGINT NOT NULL REFERENCES guests(id) ON DELETE RESTRICT,
    type         TEXT NOT NULL CHECK (type IN ('EXPORT', 'RECTIFY', 'DELETE')),
    status       TEXT NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    handled_by   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_privacy_requests_guest_id ON privacy_requests (guest_id);
CREATE INDEX idx_privacy_requests_status   ON privacy_requests (status);
CREATE INDEX idx_privacy_requests_type     ON privacy_requests (type);

CREATE TABLE personal_data_access_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    guest_id      BIGINT REFERENCES guests(id) ON DELETE SET NULL,
    action        TEXT NOT NULL CHECK (action IN ('VIEW', 'EXPORT', 'MODIFY', 'ANONYMIZE')),
    justification TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_personal_data_access_logs_guest_id   ON personal_data_access_logs (guest_id);
CREATE INDEX idx_personal_data_access_logs_user_id    ON personal_data_access_logs (user_id);
CREATE INDEX idx_personal_data_access_logs_action     ON personal_data_access_logs (action);
CREATE INDEX idx_personal_data_access_logs_created_at ON personal_data_access_logs (created_at);

ALTER TABLE guests
    ADD COLUMN do_not_contact BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_guests_do_not_contact ON guests (do_not_contact);

-- -----------------------------------------------------------------------------
-- room_stays  (V10, ER-16)
-- -----------------------------------------------------------------------------
CREATE TABLE room_stays (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    reservation_id   BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    check_in         DATE NOT NULL,
    check_out        DATE NOT NULL,
    actual_check_in  TIMESTAMPTZ,
    actual_check_out TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT room_stays_check_out_gt_check_in CHECK (check_out > check_in)
);

CREATE INDEX idx_room_stays_room_id        ON room_stays (room_id);
CREATE INDEX idx_room_stays_reservation_id ON room_stays (reservation_id);
CREATE INDEX idx_room_stays_check_in       ON room_stays (check_in);
CREATE INDEX idx_room_stays_check_out      ON room_stays (check_out);
